services:
- type: web
  name: flask
  repo: https://github.com/rycus86/prometheus_flask_exporter.git 
  env: python
  buildCommand: cd examples/sample-signals/app/;pip install -r requirements.txt
  startCommand: cd examples/sample-signals/app/;python app.py
  autoDeploy: false
- type: web
  name: prometheus
  env: docker
  autoDeploy: false
  envVars:
  - key: SCRAPE_SERVICE_NAME
    fromService:
      name: flask
      type: web
      property: host  
  - key: SCRAPE_SERVICE_PORT
    fromService:
      name: flask
      type: web
      property: port    
